version: "3.8"
services:
  app:
    env_file:
      -   .env
    build: ./etc/php/dev/
    image: devphp:8
    container_name: api
    environment:
      XDEBUG_CONFIG: "idekey=PHPSTORM remote_connect_back=0 remote_enable=1 client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=api"
      DATABASE_URL: "mysql://root:${DB_ROOT_PASSWORD}@db:3306/${DB_NAME}?serverVersion=8.0"
    volumes:
      - ./api:/var/www/html
      - ./etc/php/dev/xdebug.ini:/usr/local/etc/php/conf.d/xdebug-custom.ini
    depends_on:
      -   db
  db:
    env_file:
      -   .env
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: api_db
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "${DB_SERVER_LOCAL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: api_nginx
    volumes:
      - ./api:/var/www/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      -   app

volumes:
  db-data:

